#!/bin/bash

# compose/local/django/start

set -o errexit
set -o pipefail
set -o nounset

# Roda as migrações ao iniciar
python ./manage.py migrate

# Inicia o servidor de desenvolvimento do Django, que recarrega automaticamente
exec python ./manage.py runserver 0.0.0.0:8000



