# Generated by Django 4.2.17 on 2025-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.IntegerField(choices=[(67, 'Master'), (11, 'Usuário Básico')], default=11),
        ),
    ]
