# Generated by Django 4.2.17 on 2025-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incite", "0003_instituicao_offset_x_instituicao_offset_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="instituicao",
            name="marcador_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos_instituicoes/"
            ),
        ),
    ]
