# Generated by Django 4.2.17 on 2025-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incite', '0006_postagem_autor_postagem_imagem_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='cidade_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
