# Generated by Django 4.2.17 on 2025-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incite', '0007_instituicao_cidade_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='post_content_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
