# Generated by Django 4.2.17 on 2025-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultura', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agriculturedata',
            index=models.Index(fields=['region'], name='idx_region'),
        ),
    ]
