from django.db import models

# Create your models here.
from django.db import models

class AgricultureData(models.Model):
    pkid = models.AutoField(primary_key=True)
    muni_id = models.CharField(max_length=255, null =False, blank=False)
    year = models.IntegerField(null =False, blank=False)
    area = models.CharField(max_length=255, null =False, blank=False)
    variable = models.CharField(max_length=255, null =False, blank=False)


    total = models.FloatField(null=True, blank=True)
    abacate = models.FloatField(null=True, blank=True)
    abacaxi = models.FloatField(null=True, blank=True)
    acai = models.FloatField(null=True, blank=True)
    alfafa_fenada = models.FloatField(null=True, blank=True)
    algodao_arboreo_em_caroco = models.FloatField(null=True, blank=True)
    algodao_herbaceo_em_caroco = models.FloatField(null=True, blank=True)
    alho = models.FloatField(null=True, blank=True)
    amendoim_em_casca = models.FloatField(null=True, blank=True)
    arroz_em_casca = models.FloatField(null=True, blank=True)
    aveia_em_grao = models.FloatField(null=True, blank=True)
    azeitona = models.FloatField(null=True, blank=True)
    banana_cacho = models.FloatField(null=True, blank=True)
    batata_doce = models.FloatField(null=True, blank=True)
    batata_inglesa = models.FloatField(null=True, blank=True)
    borracha_latex_coagulado = models.FloatField(null=True, blank=True)
    borracha_latex_liquido = models.FloatField(null=True, blank=True)
    cacau_em_amendoa = models.FloatField(null=True, blank=True)
    cafe_em_grao_total = models.FloatField(null=True, blank=True)
    cafe_em_grao_arabica = models.FloatField(null=True, blank=True)
    cafe_em_grao_canephora = models.FloatField(null=True, blank=True)
    caju = models.FloatField(null=True, blank=True)
    cana_de_acucar = models.FloatField(null=True, blank=True)
    cana_para_forragem = models.FloatField(null=True, blank=True)
    caqui = models.FloatField(null=True, blank=True)
    castanha_de_caju = models.FloatField(null=True, blank=True)
    cebola = models.FloatField(null=True, blank=True)
    centeio_em_grao = models.FloatField(null=True, blank=True)
    cevada_em_grao = models.FloatField(null=True, blank=True)
    cha_da_india_folha_verde = models.FloatField(null=True, blank=True)
    coco_da_baia = models.FloatField(null=True, blank=True)
    dende_cacho_de_coco = models.FloatField(null=True, blank=True)
    erva_mate_folha_verde = models.FloatField(null=True, blank=True)
    ervilha_em_grao = models.FloatField(null=True, blank=True)
    fava_em_grao = models.FloatField(null=True, blank=True)
    feijao_em_grao = models.FloatField(null=True, blank=True)
    figo = models.FloatField(null=True, blank=True)
    fumo_em_folha = models.FloatField(null=True, blank=True)
    girassol_em_grao = models.FloatField(null=True, blank=True)
    goiaba = models.FloatField(null=True, blank=True)
    guarana_semente = models.FloatField(null=True, blank=True)
    juta_fibra = models.FloatField(null=True, blank=True)
    laranja = models.FloatField(null=True, blank=True)
    limao = models.FloatField(null=True, blank=True)
    linho_semente = models.FloatField(null=True, blank=True)
    maca = models.FloatField(null=True, blank=True)
    malva_fibra = models.FloatField(null=True, blank=True)
    mamao = models.FloatField(null=True, blank=True)
    mamona_baga = models.FloatField(null=True, blank=True)
    mandioca = models.FloatField(null=True, blank=True)
    manga = models.FloatField(null=True, blank=True)
    maracuja = models.FloatField(null=True, blank=True)
    marmelo = models.FloatField(null=True, blank=True)
    melancia = models.FloatField(null=True, blank=True)
    melao = models.FloatField(null=True, blank=True)
    milho_em_grao = models.FloatField(null=True, blank=True)
    noz_fruto_seco = models.FloatField(null=True, blank=True)
    palmito = models.FloatField(null=True, blank=True)
    pera = models.FloatField(null=True, blank=True)
    pessego = models.FloatField(null=True, blank=True)
    pimenta_do_reino = models.FloatField(null=True, blank=True)
    rami_fibra = models.FloatField(null=True, blank=True)
    sisal_ou_agave_fibra = models.FloatField(null=True, blank=True)
    soja_em_grao = models.FloatField(null=True, blank=True)
    sorgo_em_grao = models.FloatField(null=True, blank=True)
    tangerina = models.FloatField(null=True, blank=True)
    tomate = models.FloatField(null=True, blank=True)
    trigo_em_grao = models.FloatField(null=True, blank=True)
    triticale_em_grao = models.FloatField(null=True, blank=True)
    tungue_fruto_seco = models.FloatField(null=True, blank=True)
    urucum_semente = models.FloatField(null=True, blank=True)
    uva = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = "agricultura_data"
        indexes = [
            models.Index(fields=["variable"], name="idx_variable"),
            models.Index(fields=["muni_id"], name="idx_muni"),
            models.Index(fields=["year"], name="idx_year"),
        ]