#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Coleta os arquivos estáticos para o volume que o Nginx vai ler
python ./manage.py collectstatic --no-input
# Aplica as migrações do banco de dados
python ./manage.py migrate

exec  gunicorn config.wsgi --bind 0.0.0.0:8000 